# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=200)),
                ('cus_address', models.CharField(max_length=200)),
                ('cus_pincode', models.CharField(max_length=10)),
                ('cus_mobile', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chem_soap_noodles', models.CharField(max_length=200)),
                ('perfume', models.CharField(max_length=200)),
                ('packing', models.CharField(max_length=200)),
                ('machinery', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packers', models.CharField(max_length=200)),
                ('operators', models.CharField(max_length=200)),
                ('chargemen', models.CharField(max_length=200)),
                ('shiftmen', models.CharField(max_length=200)),
            ],
        ),
    ]
