# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cus_mobile',
        ),
    ]
