# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_customer_cus_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
